# MunkiReport tasks - main.yml
---
- name: create munkireport group
  group:
    name: munkireport
    system: yes

- name: create munkireport user
  user:
    name: munkireport
    comment: "MunkiReport User"
    group: munkireport
    shell: /bin/bash
    system: yes

- name: add web user (www-data) to munkireport group
  user:
    name: www-data
    groups: munkireport
    append: yes

- name: include facts tasks
  include: facts.yml

- name: install required packages - munkireport
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php7.0-fpm
    - php7.0-mbstring
    - php7.0-mysql
    - php7.0-xml
    - php7.0-zip
  
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: include mysql tasks
  include: mysql.yml

- name: clone munkireport github repo
  git:
    repo: 'https://github.com/munkireport/munkireport-php.git'
    dest: "{{ munkireport_directory }}"
    clone: yes
    update: yes
    version: "{{ munkireport_version }}"
  become_user: "{{ ansible_local.munkireport.repo.become }}"
  notify:
    - restart nginx
    - restart php7

- name: configure munkireport repo
  git_config:
    name: core.fileMode
    repo: "{{ munkireport_directory }}"
    scope: local
    value: false

- name: set munkireport repo owner
  file:
    path: "{{ munkireport_directory }}"
    owner: munkireport
    group: munkireport
    recurse: yes

- name: set munkireport repo permissions
  file:
    path: "{{ munkireport_directory }}/public"
    owner: munkireport
    group: munkireport
    mode: 0750
    recurse: yes

- name: install composer dependencies
  composer:
    command: install
    no_dev: yes
    optimize_autoloader: yes
    working_dir: "{{ munkireport_directory }}"
  become_user: munkireport
  notify:
    - restart nginx
    - restart php7

- name: modify php settings
  lineinfile:
    path: /etc/php/7.0/fpm/php.ini
    regexp: '.*cgi.fix_pathinfo='
    line: 'cgi.fix_pathinfo=0'
  notify:
    - restart nginx
    - restart php7

- name: apply munkireport config.php template
  template:
    src: config.php.j2
    dest: "{{ munkireport_directory }}/config.php"
    owner: munkireport
    group: munkireport
    mode: 0644
  notify:
    - restart nginx
    - restart php7

- name: include nginx tasks
  include: nginx.yml

- name: ensure web services are running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
    - php7.0-fpm