# MunkiReport tasks - main.yml
---
- name: create munkireport group
  group:
    name: munkireport
    system: yes

- name: create munkireport user
  user:
    name: munkireport
    comment: "MunkiReport User"
    group: munkireport
    shell: /bin/bash
    system: yes

- name: add web user (www-data) to munkireport group
  user:
    name: www-data
    groups: munkireport
    append: yes

- name: install required packages - munkireport
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php7.0-fpm
    - php7.0-mbstring
    - php7.0-mysql
    - php7.0-xml
    - php7.0-zip
  
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: include mysql tasks
  include_tasks: mysql.yml

- name: create munkireport directory
  file:
    path: "{{ munkireport_directory }}"
    state: directory
    owner: munkireport
    group: munkireport
    mode: 0750

- name: clone munkireport github repo
  git:
    repo: 'https://github.com/munkireport/munkireport-php.git'
    dest: "{{ munkireport_directory }}"
    clone: yes
    update: yes
    version: "{{ munkireport_version }}"
  become_user: munkireport
  notify:
    - restart nginx
    - restart php7
  register: clone_munkireport_repo

- name: configure munkireport repo
  git_config:
    name: core.fileMode
    repo: "{{ munkireport_directory }}"
    scope: local
    value: false
  become_user: munkireport

- name: set persmisons for munkireport sub-directories
  file:
    path: "{{ munkireport_directory }}/public"
    mode: 0750
    recurse: yes

- name: install composer dependencies
  composer:
    command: install
    no_dev: yes
    optimize_autoloader: yes
    working_dir: "{{ munkireport_directory }}"
  become_user: munkireport
  notify:
    - restart nginx
    - restart php7

- name: modify php settings
  lineinfile:
    path: /etc/php/7.0/fpm/php.ini
    regexp: '.*cgi.fix_pathinfo='
    line: 'cgi.fix_pathinfo=0'
  notify:
    - restart nginx
    - restart php7

- name: enable munkireport secure auth (ssl)
  set_fact:
    munkireport_auth_secure: "TRUE"
  when:
    - munkireport_ssl_cert_path is defined
    - munkireport_ssl_privkey_path is defined

- name: apply munkireport config.php template
  template:
    src: config.php.j2
    dest: "{{ munkireport_directory }}/config.php"
    owner: munkireport
    group: munkireport
    mode: 0640
  notify:
    - restart nginx
    - restart php7

- name: run database migrations
  command: "php {{ munkireport_directory }}/database/migrate.php"
  become_user: munkireport
  when: clone_munkireport_repo is changed

- name: include nginx tasks
  include_tasks: nginx.yml

- name: ensure web services are running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
    - php7.0-fpm
